name = "nikhils9/rewards-distribution"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'nikhils9/rewards-distribution'"

[repository]
user = "nikhils9"
project = "rewards-distribution"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.4.0"
source = "github"
